---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, Abhinav Jambulingam
# Created: Fall 2021
#
# Store Join Command as a fact
#
- name: Store join command to register
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: joinCommandOutput

- name: Store join command as a fact
  ansible.builtin.set_fact:
    joinCommand: "{{ joinCommandOutput.stdout }}"
...