---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# With Helm, add CouchDB Repo and Deploy the Chart
#
# PREREQUISITES:
#   must have helm installed on the host machine
#
# REQUIRES:
#   admin_user      - the admin username
#   admin_password  - the admin password

# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
#
#
# USE THE COMMAND
#     helm show values couchdb/couchdb
# TO INVESTIGATE IF THERE'S ANYTHING I SHOULD BE SETTING
# USE
#     kubectl logs ..... to debug/diagnose...
#
# I DID MAKE A CHANGE I DIDN'T RUN YET, SO FIRST, TRY RUNNING, SEE IF IT WORKS!!!!
#
#
# IF NOT, TRY STARTING A BARE-BONES K8S CLUSTER, UNTAINTED, (OR TAINTED AND USE 2 DB'S, JUST TO KEEP THINGS SIMPLE, FEWER VARIABLES)
#       THEN SETUP EVERYTHING MANUALLY, SEE IF IT WORKS LIKE THAT!!!!!
#
#
# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
# TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO

- name: Add CouchDB Helm Repository
  kubernetes.core.helm_repository:
    name: couchdb
    url: https://apache.github.io/couchdb-helm

# TODO: delete this after debugging
- name: debug my uuid syntax
  debug:
    var: lookup('password', '/dev/null', chars='ascii_lowercase,digits', seed=ansible_date_time.epoch)

- name: Deploy CouchDB Helm Chart
  kubernetes.core.helm:
    name: teamx-release
    chart_ref: couchdb/couchdb
    release_namespace: default
    values:
      adminUsername: "{{ admin_user }}"
      adminPassword: "{{ admin_password }}"
      podManagementPolicy: OrderedReady
      # TODO: ^^^^ necessary??? works????
      clusterSize: 1
      couchdbConfig:
        # chttpd:
        #   port: 5984
        #   require_valid_user: false
        #   bind_address: 0.0.0.0
        couchdb:
          # single_node: true
          uuid: "{{ lookup('password', '/dev/null', chars='ascii_lowercase,digits', seed=ansible_date_time.epoch) }}"
        # cluster:
        #   n: 1 # number of replicas
        #   q: 8 # number of shards

- name: Wait for all pods to be ready
  ansible.builtin.shell: kubectl get pods --namespace default -l "app=couchdb,release=teamx-release" -o json | jq -r '.items[].status.phase'
  register: pods_phases
  until: not pods_phases.stdout_lines | reject('match', '^Running$')
  retries: 6

# TODO: and then run this: (I think may be missing password/username fields, but might wanna do http://user:pswd@127.0.0.1:5984/_cluster_setup )
#   kubectl exec --namespace default teamx-release-couchdb-0 -c couchdb -- \
#     curl -s \
#     http://127.0.0.1:5984/_cluster_setup \
#     -X POST \
#     -H "Content-Type: application/json" \
#     -d '{"action": "finish_cluster"}'

# TODO: debug with:
#       kubectl logs teamx-release-couchdb-X
#           where X is one of 0,1,2
#       it's failing when couchdb@teamx-release-couchdb-N tries to talk to couchdb@......-couchdb-M
#         (where N != M)

# TODO: the "next steps" that are printed out
# and btw, what's that --from-literal and --from-file in the "kubectl create secret" command??
...


  # kubectl exec --namespace default -it teamx-release-couchdb-0 -c couchdb -- \
  #   curl -s \
  #   http://127.0.0.1:5984/_cluster_setup \
  #   -X POST \
  #   -H "Content-Type: application/json" \
  #   -d '{"action": "finish_cluster"}' \
  #   -u <adminUsername>

  # "{{ lookup('password', '/dev/null', chars='ascii_lowercase,digits', seed=ansible_date_time.epoch) }}"
