---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Run Kafka Job on a Pod
#
# REQUIRES:
#   host_url - location of the api
#   name - name of the deployment
#   container_name - name given to the container in this deployment
#   registry_ip - IP address of image registry
#   registry_port - port on which the image registry serves up container images
#   kafkaDirectory - directory where kafka is installed

- name: Deploy Zookeeper App
  vars:
    zookeeper_props_file: "{{ kafkaDirectory }}/config/zookeeper.properties"
    zookeeper_bin_file: "{{ kafkaDirectory }}/bin/kafka-server-start.sh"
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    host: "{{ host_url }}"
    name: "{{ name }}"
    resource_definition:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: zookeeper
        minReadySeconds: 5
        template:
          metadata:
            labels:
              app: zookeeper
          spec:
            restartPolicy: Always # or Never????
            # hostname: "{{ pod_hostname }}"
            # nodeSelector:
            #   kubernetes.io/hostname: "{{ node_hostname }}"
            containers:
            - name: "{{ container_name }}"
              image: "{{ registry_ip }}:{{ registry_port }}/{{ container_name }}" # {{ registry_port | default('5000') }}/{{ container_name | default('teamx-kafka-base:latest') }}"
              imagePullPolicy: Always
              ports:
              - containerPort: 2181
              command: ['daemon']
              args:
              - --
              - "{{ zookeeper_bin_file }}"
              - "{{ zookeeper_props_file }}"
...
