---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Install CouchDB and dependencies
#

- name: Add the CouchDB GPG Key
  become: yes
  ansible.builtin.apt_key:
    url: https://couchdb.apache.org/repo/keys.asc
    keyring: /usr/share/keyrings/couchdb-archive-keyring.gpg

- name: store shell output of repo line in a register variable
  ansible.builtin.shell: |
    . /etc/os-release
    echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main"
  register: repo_line_echo_cmd

- name: Add the CouchDB Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ repo_line_echo_cmd.stdout }}"
    filename: couchdb

- name: Install CouchDB
  become: yes
  ansible.builtin.apt:
    name: couchdb
...
