---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, AJ
# Created: Fall 2021
#
# Configure CouchDB
#

- name: Add admin user to CouchDB Config
  become: yes
  ansible.builtin.lineinfile:
    path: /opt/couchdb/etc/local.ini
    line: "admin = {{ password }}"
    insertafter: ^\[admins\]
    firstmatch: yes

- name: Copy default.ini over to CouchDB Instance
  become: yes
  ansible.builtin.copy:
    src: ../../../file_srcs/default.ini
    dest: /opt/couchdb/etc/default.ini
    mode: 0640

- name: Configure CouchDB's network interface
  become: yes
  ansible.builtin.lineinfile:
    path: /opt/couchdb/etc/local.ini
    line: "port = 5984\nbind_address = 0.0.0.0"
    insertafter: ^\[chttpd\]
    firstmatch: yes
...
