---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Wait for necessary connections and start Consumer
#

- name: Wait for Kafka instances
  ansible.builtin.wait_for:
    host: "{{ item }}"
    port: 9092
  loop: "{{ [zookeeperIp, couchDBIp] }}"


- name: Wait for CouchDB
  ansible.builtin.wait_for:
    host: "{{ couchDBIp }}"
    port: 5984


- name: Start Consumer
  environment:
    COUCH_DB_IP: "{{ couchDBIp }}"
    KAFKA_1_IP: "{{ zookeeperIp }}"
    KAFKA_2_IP: "{{ couchDBIp }}"
  ansible.builtin.shell: daemon python3 ~/consumer.py
...
