---
##########################################################
### Play 1: Cleanup provisioned instances
#
# Read AWS EC2 id's from variables file
# and destroy previously created instances
##########################################################

- name: Clean up provisioned Cloud Instances
  hosts: MyLocalVMs
  remote_user: ubuntu
  vars_files:
  - ./variables/path_names.yml
  - ./variables/local_var_names.yml

  tasks:
  - name: Check if Local Var Names File exists
    stat:
      path: "{{ local_vm_variables }}"
    register: local_vars_stat

  - name: destroy AWS instances
    include_tasks: ./tasks/playbook_cleanup.yml
    when: local_vars_stat.stat.exists
...
