---
# EECS 4287/5287: Principles of Cloud Computing
# Author: Adam Catalfano, AJ
# Created: Fall 2021
#
# This playbook provisions the local Instances,
# configures the producer scripts for each,
# and starts executing the producer code
#

##########################################################
### Play 1: Install Dependencies on all Producers
#
# Install python and python packages on producers
##########################################################
- name: 'Play 1: Install Dependencies on all Producers'
  hosts: AllProducers
  remote_user: vagrant
  strategy: debug

  tasks:
  - ansible.builtin.include_tasks: tasks/playbook_aptitude_upgrade.yml

  - name: Install DistUtils for Python3
    become: yes
    ansible.builtin.apt:
      name: python3-distutils

  - name: Install Pip for Python3
    ansible.builtin.shell: curl https://bootstrap.pypa.io/get-pip.py | sudo python3

  - name: Install packages required to run producer
    ansible.builtin.pip: name=kafka-python

  - name: Copy over the unconfigured producer.py script
    ansible.builtin.copy:
      mode: 0700
      src: ./file_srcs/producer.py
      dest: /home/vagrant/producer.py

##########################################################
### Play 2: Write Producer1 script
#
# Customize and write producer to Producer1
##########################################################
- name: 'Play 2: Write the Producer1 script'
  hosts: Producer1
  remote_user: vagrant
  strategy: debug
  vars_files:
  - ./variables/producer_src_config.yml
  vars:
    provisioner_ip: "{{ groups['MyLocalVMs'].0 }}"

  tasks:
  - name: Configure Producer1 Script
    vars:
      config: "{{ news }}"
      kafkaIp: "{{ hostvars[provisioner_ip]['vm2_ip'] }}"
    ansible.builtin.include_tasks: ./tasks/vms/local-vms/playbook_configure_producer_script.yml

  - name: Replace API key instances with API token

##########################################################
### Play 3: Write the Producer2 script
#
# Customize and write producer to Producer2
##########################################################
- name: 'Play 3: Write the Producer2 script'
  hosts: Producer2
  remote_user: vagrant
  strategy: debug
  vars_files:
  - ./variables/producer_src_config.yml

  tasks:
  - name: Configure Producer2 Script
    vars:
      config: "{{ weather }}"
      kafkaIp: "{{ hostvars[provisioner_ip]['vm3_ip'] }}"
    ansible.builtin.include_tasks: ./tasks/vms/local-vms/playbook_configure_producer_script.yml
# ##########################################################
# ### Play 4: Run Producer on producer VM's
# #
# # Run producer.py on both VM1.1 and VM1.2
# ##########################################################
# - name: "Play 4: Run Producer on producer VM's"
#   hosts: AllProducers
#   remote_user: vagrant
#   strategy: debug

#   tasks:
#   - TODO: run the producer!!!
...
