---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, Abhinav Jambulingam
# Created: Fall 2021
#
# configure kubeworker and join cluster
#
# REQUIRES:
#     privateIP
#     remoteMasterIP
#     joinCommandName
#

- name: Set Hostname Aliases on K8S Worker
  become: yes
  vars:
    lines:
    - "{{ inventory_hostname }} kubeworker2"
    - "{{ privateIP | default('127.0.0.1') }} kubeworker2"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ lines | join('\n') }}"

- name: debug hostvars
  debug:
    var: hostvars

- name: debug inventory hostname
  debug:
    msg: "{{ inventory_hostname }}"
- name: debug ansible facts
  debug:
    msg: "{{ ansible_facts }}"

- name: Join K8S Cluster
  become: yes
  # vars:
  #   joinCommand: "{{ hostvars[inventory_hostname][joinCommandName] }}" #"{{ lookup('vars', joinCommandName, default='') }}"
  ansible.builtin.shell: "{{ joinCommand }} --node-name kubeworker2"
  when: joinCommand
...
