---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, Abhinav Jambulingam
# Created: Fall 2021
#
# Start k8s master, add flannel network virtualization
#
- name: Start k8s control plane
  become: yes
  ansible.builtin.shell: kubeadm init --node-name kubemaster --pod-network-cidr=10.244.0.0/16


- name: Make the ~/.kube directory
  ansible.builtin.file:
    state: directory
    path: ~/.kube

- name: Copy over the k8s config file into the ~/.kube directory
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu

- name: Add Flannel Network Virtualization
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
...