---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Write the created instances to an inventory file, deleting it first if it exists
#
# NOTE: Requires ec2.instance_ids to be loaded up with the EC2 ID's
#

- name: Include Path Name Vars
  include_vars: ../variables/path_names.yml

- name: Delete Local Variables File if exists
  file:
    path: "{{ local_vm_variables }}"
    state: absent

- name: Include Group Name Vars
  include_vars: ../variables/group_names.yml

- name: Include Local Var Names
  include_vars: ../variables/local_var_names.yml

- name: Write EC2 ID's to Variables File as an array variable
  lineinfile:
    path: "{{ local_vm_variables }}"
    line: "---\n{{ running_instance_ids }}: {{ hostvars[inventory_hostname].ec2.instance_ids }}\n..."
    create: yes
...