# Author: Adam Catalfano, Abhinav Jambulingam
# Vanderbilt University
# Created December 2021
#
FROM ubuntu:latest

# RUN apt-get -y update && apt-get install -y net-tools python3 gcc
# RUN apt-get install -y python3-dev python3-pip
# RUN python3 -m pip install --upgrade pip
# RUN pip3 install --upgrade numpy
# RUN pip3 install --upgrade pyzmq
# RUN mkdir /kafka_
# RUN wget https://dlcdn.apache.org/kafka/3.0.0/kafka-3.0.0-src.tgz
# RUN tar -xzf kafka-3.0.0-src.tgz /kafka_
# TODO: any other deps???

# TODO: config consumer.py's kafka IP's (2 and 3 eventually)
# TODO: likewise, modify consumer.py to be more editable (or use env vars! can add with docker maybe???)
# TODO: use ENV
# ENV
# prob separate it out w/ ':' characters

COPY ./consumer.py /
RUN apt-get update && apt-get install -y python3 net-tools gcc
RUN apt-get install -y python3-dev python3-pip
RUN apt-get pip install --upgrade pip
RUN pip3 install jsbeautifier kafka-python CouchDB