---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, AJ
# Created: Fall 2021
#
# Start the Kafka server as a daemon
#

- name: Wait for zookeeper to bring up port 2181 on VM3
  ansible.builtin.wait_for:
    host: "{{ zookeeper_ip }}"
    port: 2181

- name: Start Kafka as a daemon process
  ansible.builtin.shell: 'daemon -- {{ kafka_directory }}/bin/kafka-server-start.sh {{ kafka_directory }}/config/server.properties'
...
