# Author: Adam Catalfano
# Vanderbilt University
# Created December 2021
#
FROM ubuntu:latest

RUN mkdir /kafka_
ADD https://dlcdn.apache.org/kafka/3.0.0/kafka-3.0.0-src.tgz /
RUN tar -xzf kafka-3.0.0-src.tgz -C /kafka_
