---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Install Kafka and Dependencies
#

- name: Install OpenJDK
  become: yes
  ansible.builtin.apt: name=openjdk-11-jdk

- name: Include Path-Name Vars
  ansible.builtin.include_vars: ../../../variables/path_names.yml

- name: Make directory for Kafka installation
  ansible.builtin.file:
    state: directory
    path: "{{ kafkaDirectory }}"

- name: Extract archive into target Kafka install directory
  ansible.builtin.unarchive:
    src: https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz
    dest: "{{ kafkaDirectory }}"
    remote_src: yes
    extra_opts:
    - --strip-components
    - 1
...
