---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      restartPolicy: Always
      containers:
      - name: couchdb
        image: 127.0.0.1:5000/teamx-couchdb:latest
        imagePullPolicy: Always
        env:
        - name: COUCHDB_USER
          value: admUser
        - name: COUCHDB_PASSWORD
          value: admPassword
        ports:
        - containerPort: 5984
        # TODO: doubt it vvvv
        # - epmd: 4369
        # - cdbCluster: 9100
        # TODO: call this from ansible.builtin.shell w/ kubectl exec .....
        #           ...or not, might not matter at all!
        # command: [curl]
        # args:
        # - -X
        # - PUT
        # - http://admUser:admPassword@127.0.0.1:5984/_global_changes
...


# kubectl get pod -l app=couchdb -o json | jq -r '.items[0].metadata.name'
#  >>> POD-NAME
# (no surrounding quotes with -r option)

# download and install helm:
#   curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
#   echo "deb https://baltocdn.com/helm/stable/debian all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
#   sudo apt-get update
#   sudo apt-get -y install helm


# helm repo add couchdb https://apache.github.io/couchdb-helm

# helm install teamx-release couchdb/couchdb \
#   --set allowAdminParty=true \
#   --set couchdbConfig.couchdb.uuid=$(curl https://www.uuidgenerator.net/api/version4 2>/dev/null | tr -d -)


# TODO: TODO: TODO:
#   rn doing it the helm way, the "-c" part of last "exec" cmd fails b/c
#       not starting containers since not provided with a COUCHDB_PASSWORD or COUCHDB_USER!!!
#                     ^^^^^ ANYWAY TO PROVIDE THESE ENV CONFIGS? OR AM I MISSING IT IN THE SETUP INSTRUCTIONS???
#                             (or maybe just take what you're missing from the helm src!!!!)
#
#     look here about "expose types" (i.e. service types) https://itnext.io/kubernetes-clusterip-vs-nodeport-vs-loadbalancer-services-and-ingress-an-overview-with-722a07f3cfe1
#       here about couchdb helm https://docs.couchdb.org/en/stable/install/kubernetes.html
#         and here https://artifacthub.io/packages/helm/couchdb/couchdb
#             ^^^^ see the configuration section at the bottom...seems user/pswd should be getting provided rn??????
#                                               https://artifacthub.io/packages/helm/couchdb/couchdb#configuration
#
#     QUICK LINK TO THE BOX PRESENTATION!!!! https://vanderbilt.app.box.com/s/n9kfkez0yvgq1vzugak59grdq0ks334j/file/729744520505

# TODO: TODO: TODO:
#     when done manually seems to work, but still can't access it from outside???? does it need some other port enabled????
#         or port forwarding????
#         checkout that one itnext.io link and look at documentation on service-types on kubernetes site!



# Apache CouchDB is starting. Check the status of the Pods using:

#   kubectl get pods --namespace default -l "app=couchdb,release=teamx-release"
#
#   actually do this one!
#
#   kubectl get pods --namespace default -l "app=couchdb,release=teamx-release" -o json | jq '.items[].status.phase' -r
#       >>>> 3 lines reading "Running" (when it works!)

# kubectl get pods -l app=couchdb -o json | jq -r '.items[0].spec.containers[0].name'
#   for the "-c" argument down there vvvvvv (when you run this the non-helm way)

# Once all of the Pods are fully Ready, execute the following command to create
# some required system databases:

#   kubectl exec --namespace default teamx-release-couchdb-0 -c couchdb -- \
#     curl -s \
#     http://127.0.0.1:5984/_cluster_setup \
#     -X POST \
#     -H "Content-Type: application/json" \
#     -d '{"action": "finish_cluster"}'