---
# Author: Adam Catalfano
# Vanderbilt University
# Created December 2021
#

apiVersion: batch/v1
kind: Job
metadata:
  name: couch-db-job
spec:
  template:
    metadata:
      labels:
        app: consumer-pipeline-app
    spec:
      hostname: couchdb-server-host
      nodeSelector:
        kubernetes.io/hostname: kubeworker2
      containers:
      - name: teamx-couchdb
        image: 127.0.0.1:5000/teamx-couchdb
        imagePullPolicy: Always
        command:
        - service
        args:
        - couchdb
        - start
      restartPolicy: Never


#   type: NodePort
#   selector:
#     app: consumer-pipeline-app
#   ports:
#   - name: couchdb-port
#     port: 5984
#     targetPort: 5984
#     nodePort: 30000
...
