---
# Author: Adam Catalfano
# Vanderbilt University
# Created December 2021
#

apiVersion: v1
kind: Service
metadata:
  name: couch-db-svc
spec:
  type: NodePort
  selector:
    app: consumer-pipeline-app
  ports:
  - name: couchdb-port
    port: 5984
    targetPort: 5984
    nodePort: 30000
...
