---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Deploy Kafka Service
#
# REQUIRES:
#   host_url - location of the api
#   name - name of the service
#   app_name - app that the ports are a part of
#   port_id - an offset used to calculate the physically exposed port number
#

- name: Deploy Kafka Service
  kubernetes.core.k8s_service:
    host: "{{ host_url }}"
    name: "{{ name }}"
    selector:
      app: "{{ app_name }}"
    ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: "{{ 30000 + port_id }}"
...
