---
# variables leveraged to configure
# the base producer.py python source code
weather:
  topic: weather
  base_url: http://api.weatherunlocked.com
  endpoint: /api/current/
  app_id: 5555593e
  api_key: 14054547b923223520f080c7f4747266
  url_options: f'40.71,-74.00?app_id={app_id}&app_key={api_key}'

news:
  topic: news
  base_url: http://api.thenewsapi.com
  endpoint: /v1/news/top
  api_key: tNbyCyqzlJLr9as0h54cTZddSi7UZft2Ukjowmjj
  urlOptions: f'?api_token={api_key}&locale=us'
...
