---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Create EC2 instances on AWS
#

- name: Include Group Name variables
  ansible.builtin.include_vars: ../../variables/group_names.yml

- name: Include AWS variables
  ansible.builtin.include_vars: ../../variables/aws_vars.yml

- name: Provision master/vm2 instance
  vars:
    name: master_vm2
    instance_flavor: "{{ master_instance_type }}"
    instance_fact_name: master_instance
    sec_group_list:
    - "{{ ssh_SG.name }}"
    - "{{ ftp_SG.name }}"
    - "{{ http_SG.name }}"
    - "{{ k8s_control_SG.name }}"
    - "{{ flannel_SG.name }}"
    - "{{ docker_private_registry_SG.name }}"
    - "{{ zookeeper_SG.name }}"
    - "{{ kafka_SG.name }}"
    - "{{ couch_db_SG.name }}"
    # TODO:vvv (do I need this????)
    - "{{ k8s_api_egress_SG.name }}"
    - "{{ test_all_SG.name }}"
  ansible.builtin.include_tasks: ./playbook_provision_aws_template.yml

- name: Provision vm3 (non-master) instance
  vars:
    name: worker_vm3
    instance_flavor: "{{ worker_instance_type }}"
    instance_fact_name: regular_instance
    sec_group_list:
    - "{{ ssh_SG.name }}"
    - "{{ ftp_SG.name }}"
    - "{{ http_SG.name }}"
    - "{{ couch_db_SG.name }}"
    - "{{ k8s_worker_SG.name }}"
    - "{{ flannel_SG.name }}"
    - "{{ docker_private_registry_SG.name }}"
    - "{{ zookeeper_SG.name }}"
    - "{{ kafka_SG.name }}"
    - "{{ k8s_api_egress_SG.name }}"
    - "{{ test_all_SG.name }}"
  ansible.builtin.include_tasks: ./playbook_provision_aws_template.yml

- name: Add new instances to all_remote group
  ansible.builtin.add_host:
    hostname: "{{ item.public_ip_address }}"
    groupname: "{{ all_remote }}"
  loop: [ "{{ master_instance }}", "{{ regular_instance }}" ]

- name: Add instances to appropriate vm2 and vm3 groups
  ansible.builtin.add_host:
    hostname: "{{ item.0.public_ip_address }}"
    groupname: "{{ item.1 }}"
  with_together:
  - [ "{{ master_instance }}", "{{ regular_instance }}" ]
  - [ "{{ kafka1_zookeeper_consumer }}", "{{ kafka2_couchDB }}" ]

- name: set ips as facts
  ansible.builtin.set_fact:
    "{{ zookeeper_ip }}": "{{ master_instance.public_ip_address }}"
    "{{ couchdb_ip }}": "{{ regular_instance.public_ip_address }}"
    "{{ zookeeper_private_ip }}": "{{ master_instance.private_ip_address }}"
    "{{ couchdb_private_ip }}": "{{ regular_instance.private_ip_address }}"

- name: Pause for deployment
  ansible.builtin.pause:
    seconds: 30

- name: Wait for SSH to come up
  debugger: on_failed
  delegate_to: "{{ item.public_dns_name }}"
  ansible.builtin.wait_for:
    timeout: 60
    port: 22
    state: started
  loop: [ "{{ master_instance }}", "{{ regular_instance }}" ]

- name: Include Local Var Names
  ansible.builtin.include_vars: ../../variables/local_var_names.yml

- name: Set IDs Fact
  ansible.builtin.set_fact:
    key_value: "{{ running_instance_ids }}: [ {{ master_instance }}, {{ regular_instance }} ]"


- name: Write EC2 IDs to local variables file
  vars:
    instance_ids:
    - "{{ master_instance.instance_id }}"
    - "{{ regular_instance.instance_id }}"
  ansible.builtin.include_tasks: ../playbook_write_local_vars_file.yml
...
