---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, AJ
# Created: Fall 2021
#
# Create EC2 instances on AWS
#

- name: Include AWS variables
  ansible.builtin.include_vars: ../../variables/aws_vars.yml

- name: Include Group Name variables
  ansible.builtin.include_vars: ../../variables/group_names.yml

- name: Provision AWS instances
  amazon.aws.ec2:
    key_name: "{{ key_name }}"
    group: "{{ security_groups }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
    count: 2
  register: ec2

- name: Add new instances to all_remote group
  ansible.builtin.add_host:
    hostname: "{{ item.public_ip }}"
    groupname: "{{ all_remote }}"
  loop: "{{ ec2.instances }}"

- name: Add instances to appropriate vm2 and vm3 groups
  ansible.builtin.add_host:
    hostname: "{{ item.0.public_ip }}"
    groupname: "{{ item.1 }}"
  with_together:
    - "{{ ec2.instances }}"
    - [ "{{ kafka1_zookeeper_consumer }}", "{{ kafka2_couchDB }}" ]

- name: set ips as facts
  ansible.builtin.set_fact:
    "{{ zookeeper_ip }}": "{{ ec2.instances.0.public_ip }}"
    "{{ couchdb_ip }}": "{{ ec2.instances.1.public_ip }}"

- name: Pause for deployment
  ansible.builtin.pause:
    seconds: 30

- name: Wait for SSH to come up
  debugger: on_failed
  delegate_to: "{{ item.public_dns_name }}"
  ansible.builtin.wait_for:
    timeout: 60
    port: 22
    state: started
  loop: "{{ ec2.instances }}"

- name: Include Local Var Names
  ansible.builtin.include_vars: ../../variables/local_var_names.yml

- name: Set IDs Fact
  ansible.builtin.set_fact:
    key_value: "{{ running_instance_ids }}: {{ ec2.instances }}"

- name: Write EC2 IDs to local variables file
  ansible.builtin.include_tasks: ../playbook_write_local_vars_file.yml
...
