---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano
# Created: Fall 2021
#
# Deploy a k8s service and then a pod
#
# REQUIRES: svc_path, pod_path

- name: Install jq if not installed
  become: yes
  ansible.builtin.apt: name=jq

- name: Deploy the service and pod
  ansible.builtin.shell: "kubectl apply -f {{ item }}"
  loop:
  - "{{ svc_path }}"
  - "{{ pod_path }}"

- name: Wait for the pod to be ready
  ansible.builtin.shell: kubectl get pods -o json | jq '.items[].status.phase'
  register: statuses
  until: not statuses.stdout_lines | reject('equalto', '"Running"')
  retries: 6
...
