---
#
# EECS 5287: Principles of Cloud Computing
# Author: Adam Catalfano, AJ
# Created: Fall 2021
#
# install kubernetes + docker
#

- name: Create daemon.json and write insecure registries config
  become: yes
  ansible.builtin.lineinfile:
    create: yes
    line: "{{ { 'insecure-registries': [inventory_hostname + ':5000'] } | to_json }}"
    #line: "{\n\t\"insecure-registries\": [\"{{ inventory_hostname }}:5000\"]\n}"
    path: /etc/docker/daemon.json

- name: Add Kubernetes GPG Key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install Docker and Kubernetes
  become: yes
  ansible.builtin.apt:
    name:
    - docker.io
    - kubeadm
    - kubelet
    - kubectl
    - kubernetes-cni

- name: Configure docker to use systemd-based Cgroup driver
  become: yes
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '(^ExecStart\b.*)$'
    line: '\1 --exec-opt native.cgroupdriver=systemd'
    backrefs: yes

- name: Add user to docker group
  become: yes
  ansible.builtin.user:
    append: yes
    user: ubuntu
    groups:
    - docker

- name: Change permissions for docker.sock file
  become: yes
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: 0666

- name: Reload Daemon
  become: yes
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart docker

# - name: Restart docker
#   become: yes
#   ansible.builtin.service:
#     name: docker
#     state: restarted
# - name: restart docker
#   become: yes
#   ansible.builtin.shell: |
#     systemctl daemon-reload
#     systemctl restart docker
#     systemctl enable docker
...
